{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4a086c58-80f3-4d5e-b202-30b3d794ce48",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.2\n",
      "  warnings.warn(f\"A NumPy version >={np_minversion} and <{np_maxversion}\"\n"
     ]
    }
   ],
   "source": [
    "import nltk"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "70d1b4a8-a437-4997-b700-5b533b73142b",
   "metadata": {},
   "outputs": [],
   "source": [
    "from nltk.corpus import stopwords\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "36d0ffbe-85f2-488b-8493-27b000bd6240",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package stopwords to\n",
      "[nltk_data]     /home/nhom6nth/nltk_data...\n",
      "[nltk_data]   Package stopwords is already up-to-date!\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import nltk\n",
    "nltk.download('stopwords')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b2d51d59-2caa-44bb-8d72-6c55824aeb62",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', \"you're\", \"you've\", \"you'll\", \"you'd\", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', \"she's\", 'her', 'hers', 'herself', 'it', \"it's\", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', \"that'll\", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', \"don't\", 'should', \"should've\", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', \"aren't\", 'couldn', \"couldn't\", 'didn', \"didn't\", 'doesn', \"doesn't\", 'hadn', \"hadn't\", 'hasn', \"hasn't\", 'haven', \"haven't\", 'isn', \"isn't\", 'ma', 'mightn', \"mightn't\", 'mustn', \"mustn't\", 'needn', \"needn't\", 'shan', \"shan't\", 'shouldn', \"shouldn't\", 'wasn', \"wasn't\", 'weren', \"weren't\", 'won', \"won't\", 'wouldn', \"wouldn't\"]\n"
     ]
    }
   ],
   "source": [
    "print(stopwords.words(\"english\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b90ebe66-d3e1-4ad6-84f7-cb6f2a1185f1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "#\n",
      "#  stopwords.txt\n",
      "#\n",
      "#  Freely available stopword list, balancing coverage and size.\n",
      "#\n",
      "#  From http://www.lextek.com/manuals/onix/stopwords1.html\n",
      "a\n",
      "about\n",
      "above\n",
      "across\n",
      "after\n",
      "again\n",
      "against\n",
      "all\n",
      "almost\n",
      "alone\n",
      "along\n",
      "already\n",
      "also\n",
      "although\n",
      "always\n",
      "among\n",
      "an\n",
      "and\n",
      "another\n",
      "any\n",
      "anybody\n",
      "anyone\n",
      "anything\n",
      "anywhere\n",
      "are\n",
      "area\n",
      "areas\n",
      "around\n",
      "as\n",
      "ask\n",
      "asked\n",
      "asking\n",
      "asks\n",
      "at\n",
      "away\n",
      "b\n",
      "back\n",
      "backed\n",
      "backing\n",
      "backs\n",
      "be\n",
      "became\n",
      "because\n",
      "become\n",
      "becomes\n",
      "been\n",
      "before\n",
      "began\n",
      "behind\n",
      "being\n",
      "beings\n",
      "best\n",
      "better\n",
      "between\n",
      "big\n",
      "both\n",
      "but\n",
      "by\n",
      "c\n",
      "came\n",
      "can\n",
      "cannot\n",
      "case\n",
      "cases\n",
      "certain\n",
      "certainly\n",
      "clear\n",
      "clearly\n",
      "come\n",
      "could\n",
      "d\n",
      "did\n",
      "differ\n",
      "different\n",
      "differently\n",
      "do\n",
      "does\n",
      "done\n",
      "down\n",
      "down\n",
      "downed\n",
      "downing\n",
      "downs\n",
      "during\n",
      "e\n",
      "each\n",
      "early\n",
      "either\n",
      "end\n",
      "ended\n",
      "ending\n",
      "ends\n",
      "enough\n",
      "even\n",
      "evenly\n",
      "ever\n",
      "every\n",
      "everybody\n",
      "everyone\n",
      "everything\n",
      "everywhere\n",
      "f\n",
      "face\n",
      "faces\n",
      "fact\n",
      "facts\n",
      "far\n",
      "felt\n",
      "few\n",
      "find\n",
      "finds\n",
      "first\n",
      "for\n",
      "four\n",
      "from\n",
      "full\n",
      "fully\n",
      "further\n",
      "furthered\n",
      "furthering\n",
      "furthers\n",
      "g\n",
      "gave\n",
      "general\n",
      "generally\n",
      "get\n",
      "gets\n",
      "give\n",
      "given\n",
      "gives\n",
      "go\n",
      "going\n",
      "good\n",
      "goods\n",
      "got\n",
      "great\n",
      "greater\n",
      "greatest\n",
      "group\n",
      "grouped\n",
      "grouping\n",
      "groups\n",
      "h\n",
      "had\n",
      "has\n",
      "have\n",
      "having\n",
      "he\n",
      "her\n",
      "here\n",
      "herself\n",
      "high\n",
      "high\n",
      "high\n",
      "higher\n",
      "highest\n",
      "him\n",
      "himself\n",
      "his\n",
      "how\n",
      "however\n",
      "i\n",
      "if\n",
      "important\n",
      "in\n",
      "interest\n",
      "interested\n",
      "interesting\n",
      "interests\n",
      "into\n",
      "is\n",
      "it\n",
      "its\n",
      "itself\n",
      "j\n",
      "just\n",
      "k\n",
      "keep\n",
      "keeps\n",
      "kind\n",
      "knew\n",
      "know\n",
      "known\n",
      "knows\n",
      "l\n",
      "large\n",
      "largely\n",
      "last\n",
      "later\n",
      "latest\n",
      "least\n",
      "less\n",
      "let\n",
      "lets\n",
      "like\n",
      "likely\n",
      "long\n",
      "longer\n",
      "longest\n",
      "m\n",
      "made\n",
      "make\n",
      "making\n",
      "man\n",
      "many\n",
      "may\n",
      "me\n",
      "member\n",
      "members\n",
      "men\n",
      "might\n",
      "more\n",
      "most\n",
      "mostly\n",
      "mr\n",
      "mrs\n",
      "much\n",
      "must\n",
      "my\n",
      "myself\n",
      "n\n",
      "necessary\n",
      "need\n",
      "needed\n",
      "needing\n",
      "needs\n",
      "never\n",
      "new\n",
      "new\n",
      "newer\n",
      "newest\n",
      "next\n",
      "no\n",
      "nobody\n",
      "non\n",
      "noone\n",
      "not\n",
      "nothing\n",
      "now\n",
      "nowhere\n",
      "number\n",
      "numbers\n",
      "o\n",
      "of\n",
      "off\n",
      "often\n",
      "old\n",
      "older\n",
      "oldest\n",
      "on\n",
      "once\n",
      "one\n",
      "only\n",
      "open\n",
      "opened\n",
      "opening\n",
      "opens\n",
      "or\n",
      "order\n",
      "ordered\n",
      "ordering\n",
      "orders\n",
      "other\n",
      "others\n",
      "our\n",
      "out\n",
      "over\n",
      "p\n",
      "part\n",
      "parted\n",
      "parting\n",
      "parts\n",
      "per\n",
      "perhaps\n",
      "place\n",
      "places\n",
      "point\n",
      "pointed\n",
      "pointing\n",
      "points\n",
      "possible\n",
      "present\n",
      "presented\n",
      "presenting\n",
      "presents\n",
      "problem\n",
      "problems\n",
      "put\n",
      "puts\n",
      "q\n",
      "quite\n",
      "r\n",
      "rather\n",
      "really\n",
      "right\n",
      "right\n",
      "room\n",
      "rooms\n",
      "s\n",
      "said\n",
      "same\n",
      "saw\n",
      "say\n",
      "says\n",
      "second\n",
      "seconds\n",
      "see\n",
      "seem\n",
      "seemed\n",
      "seeming\n",
      "seems\n",
      "sees\n",
      "several\n",
      "shall\n",
      "she\n",
      "should\n",
      "show\n",
      "showed\n",
      "showing\n",
      "shows\n",
      "side\n",
      "sides\n",
      "since\n",
      "small\n",
      "smaller\n",
      "smallest\n",
      "so\n",
      "some\n",
      "somebody\n",
      "someone\n",
      "something\n",
      "somewhere\n",
      "state\n",
      "states\n",
      "still\n",
      "still\n",
      "such\n",
      "sure\n",
      "t\n",
      "take\n",
      "taken\n",
      "than\n",
      "that\n",
      "the\n",
      "their\n",
      "them\n",
      "then\n",
      "there\n",
      "therefore\n",
      "these\n",
      "they\n",
      "thing\n",
      "things\n",
      "think\n",
      "thinks\n",
      "this\n",
      "those\n",
      "though\n",
      "thought\n",
      "thoughts\n",
      "three\n",
      "through\n",
      "thus\n",
      "to\n",
      "today\n",
      "together\n",
      "too\n",
      "took\n",
      "toward\n",
      "turn\n",
      "turned\n",
      "turning\n",
      "turns\n",
      "two\n",
      "u\n",
      "under\n",
      "until\n",
      "up\n",
      "upon\n",
      "us\n",
      "use\n",
      "used\n",
      "uses\n",
      "v\n",
      "very\n",
      "w\n",
      "want\n",
      "wanted\n",
      "wanting\n",
      "wants\n",
      "was\n",
      "way\n",
      "ways\n",
      "we\n",
      "well\n",
      "wells\n",
      "went\n",
      "were\n",
      "what\n",
      "when\n",
      "where\n",
      "whether\n",
      "which\n",
      "while\n",
      "who\n",
      "whole\n",
      "whose\n",
      "why\n",
      "will\n",
      "with\n",
      "within\n",
      "without\n",
      "work\n",
      "worked\n",
      "working\n",
      "works\n",
      "would\n",
      "x\n",
      "y\n",
      "year\n",
      "years\n",
      "yet\n",
      "you\n",
      "young\n",
      "younger\n",
      "youngest\n",
      "your\n",
      "yours\n",
      "z\n",
      "\n"
     ]
    }
   ],
   "source": [
    "file_path = 'stopwords.txt'\n",
    "with open(file_path, 'r') as file:\n",
    "    stpword = file.read()\n",
    "\n",
    "print(stpword)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "0a78527e-11f3-4e86-90d4-20194982c766",
   "metadata": {},
   "outputs": [],
   "source": [
    "stpword=stpword.lower()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "28d7a897-db45-45dc-aabf-6cf9f3dc313d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "#\n",
      "#  stopwords.txt\n",
      "#\n",
      "#  freely available stopword list, balancing coverage and size.\n",
      "#\n",
      "#  from http://www.lextek.com/manuals/onix/stopwords1.html\n",
      "a\n",
      "about\n",
      "above\n",
      "across\n",
      "after\n",
      "again\n",
      "against\n",
      "all\n",
      "almost\n",
      "alone\n",
      "along\n",
      "already\n",
      "also\n",
      "although\n",
      "always\n",
      "among\n",
      "an\n",
      "and\n",
      "another\n",
      "any\n",
      "anybody\n",
      "anyone\n",
      "anything\n",
      "anywhere\n",
      "are\n",
      "area\n",
      "areas\n",
      "around\n",
      "as\n",
      "ask\n",
      "asked\n",
      "asking\n",
      "asks\n",
      "at\n",
      "away\n",
      "b\n",
      "back\n",
      "backed\n",
      "backing\n",
      "backs\n",
      "be\n",
      "became\n",
      "because\n",
      "become\n",
      "becomes\n",
      "been\n",
      "before\n",
      "began\n",
      "behind\n",
      "being\n",
      "beings\n",
      "best\n",
      "better\n",
      "between\n",
      "big\n",
      "both\n",
      "but\n",
      "by\n",
      "c\n",
      "came\n",
      "can\n",
      "cannot\n",
      "case\n",
      "cases\n",
      "certain\n",
      "certainly\n",
      "clear\n",
      "clearly\n",
      "come\n",
      "could\n",
      "d\n",
      "did\n",
      "differ\n",
      "different\n",
      "differently\n",
      "do\n",
      "does\n",
      "done\n",
      "down\n",
      "down\n",
      "downed\n",
      "downing\n",
      "downs\n",
      "during\n",
      "e\n",
      "each\n",
      "early\n",
      "either\n",
      "end\n",
      "ended\n",
      "ending\n",
      "ends\n",
      "enough\n",
      "even\n",
      "evenly\n",
      "ever\n",
      "every\n",
      "everybody\n",
      "everyone\n",
      "everything\n",
      "everywhere\n",
      "f\n",
      "face\n",
      "faces\n",
      "fact\n",
      "facts\n",
      "far\n",
      "felt\n",
      "few\n",
      "find\n",
      "finds\n",
      "first\n",
      "for\n",
      "four\n",
      "from\n",
      "full\n",
      "fully\n",
      "further\n",
      "furthered\n",
      "furthering\n",
      "furthers\n",
      "g\n",
      "gave\n",
      "general\n",
      "generally\n",
      "get\n",
      "gets\n",
      "give\n",
      "given\n",
      "gives\n",
      "go\n",
      "going\n",
      "good\n",
      "goods\n",
      "got\n",
      "great\n",
      "greater\n",
      "greatest\n",
      "group\n",
      "grouped\n",
      "grouping\n",
      "groups\n",
      "h\n",
      "had\n",
      "has\n",
      "have\n",
      "having\n",
      "he\n",
      "her\n",
      "here\n",
      "herself\n",
      "high\n",
      "high\n",
      "high\n",
      "higher\n",
      "highest\n",
      "him\n",
      "himself\n",
      "his\n",
      "how\n",
      "however\n",
      "i\n",
      "if\n",
      "important\n",
      "in\n",
      "interest\n",
      "interested\n",
      "interesting\n",
      "interests\n",
      "into\n",
      "is\n",
      "it\n",
      "its\n",
      "itself\n",
      "j\n",
      "just\n",
      "k\n",
      "keep\n",
      "keeps\n",
      "kind\n",
      "knew\n",
      "know\n",
      "known\n",
      "knows\n",
      "l\n",
      "large\n",
      "largely\n",
      "last\n",
      "later\n",
      "latest\n",
      "least\n",
      "less\n",
      "let\n",
      "lets\n",
      "like\n",
      "likely\n",
      "long\n",
      "longer\n",
      "longest\n",
      "m\n",
      "made\n",
      "make\n",
      "making\n",
      "man\n",
      "many\n",
      "may\n",
      "me\n",
      "member\n",
      "members\n",
      "men\n",
      "might\n",
      "more\n",
      "most\n",
      "mostly\n",
      "mr\n",
      "mrs\n",
      "much\n",
      "must\n",
      "my\n",
      "myself\n",
      "n\n",
      "necessary\n",
      "need\n",
      "needed\n",
      "needing\n",
      "needs\n",
      "never\n",
      "new\n",
      "new\n",
      "newer\n",
      "newest\n",
      "next\n",
      "no\n",
      "nobody\n",
      "non\n",
      "noone\n",
      "not\n",
      "nothing\n",
      "now\n",
      "nowhere\n",
      "number\n",
      "numbers\n",
      "o\n",
      "of\n",
      "off\n",
      "often\n",
      "old\n",
      "older\n",
      "oldest\n",
      "on\n",
      "once\n",
      "one\n",
      "only\n",
      "open\n",
      "opened\n",
      "opening\n",
      "opens\n",
      "or\n",
      "order\n",
      "ordered\n",
      "ordering\n",
      "orders\n",
      "other\n",
      "others\n",
      "our\n",
      "out\n",
      "over\n",
      "p\n",
      "part\n",
      "parted\n",
      "parting\n",
      "parts\n",
      "per\n",
      "perhaps\n",
      "place\n",
      "places\n",
      "point\n",
      "pointed\n",
      "pointing\n",
      "points\n",
      "possible\n",
      "present\n",
      "presented\n",
      "presenting\n",
      "presents\n",
      "problem\n",
      "problems\n",
      "put\n",
      "puts\n",
      "q\n",
      "quite\n",
      "r\n",
      "rather\n",
      "really\n",
      "right\n",
      "right\n",
      "room\n",
      "rooms\n",
      "s\n",
      "said\n",
      "same\n",
      "saw\n",
      "say\n",
      "says\n",
      "second\n",
      "seconds\n",
      "see\n",
      "seem\n",
      "seemed\n",
      "seeming\n",
      "seems\n",
      "sees\n",
      "several\n",
      "shall\n",
      "she\n",
      "should\n",
      "show\n",
      "showed\n",
      "showing\n",
      "shows\n",
      "side\n",
      "sides\n",
      "since\n",
      "small\n",
      "smaller\n",
      "smallest\n",
      "so\n",
      "some\n",
      "somebody\n",
      "someone\n",
      "something\n",
      "somewhere\n",
      "state\n",
      "states\n",
      "still\n",
      "still\n",
      "such\n",
      "sure\n",
      "t\n",
      "take\n",
      "taken\n",
      "than\n",
      "that\n",
      "the\n",
      "their\n",
      "them\n",
      "then\n",
      "there\n",
      "therefore\n",
      "these\n",
      "they\n",
      "thing\n",
      "things\n",
      "think\n",
      "thinks\n",
      "this\n",
      "those\n",
      "though\n",
      "thought\n",
      "thoughts\n",
      "three\n",
      "through\n",
      "thus\n",
      "to\n",
      "today\n",
      "together\n",
      "too\n",
      "took\n",
      "toward\n",
      "turn\n",
      "turned\n",
      "turning\n",
      "turns\n",
      "two\n",
      "u\n",
      "under\n",
      "until\n",
      "up\n",
      "upon\n",
      "us\n",
      "use\n",
      "used\n",
      "uses\n",
      "v\n",
      "very\n",
      "w\n",
      "want\n",
      "wanted\n",
      "wanting\n",
      "wants\n",
      "was\n",
      "way\n",
      "ways\n",
      "we\n",
      "well\n",
      "wells\n",
      "went\n",
      "were\n",
      "what\n",
      "when\n",
      "where\n",
      "whether\n",
      "which\n",
      "while\n",
      "who\n",
      "whole\n",
      "whose\n",
      "why\n",
      "will\n",
      "with\n",
      "within\n",
      "without\n",
      "work\n",
      "worked\n",
      "working\n",
      "works\n",
      "would\n",
      "x\n",
      "y\n",
      "year\n",
      "years\n",
      "yet\n",
      "you\n",
      "young\n",
      "younger\n",
      "youngest\n",
      "your\n",
      "yours\n",
      "z\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(stpword)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "ce850b56-901f-4e55-b31b-113b808e89cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "stopwords=set(stopwords.words(\"english\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "cb52a6e7-4cf9-4485-9168-6427443299d0",
   "metadata": {},
   "outputs": [],
   "source": [
    "from nltk.tokenize import word_tokenize"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "eba340cc-0f12-4281-8d63-e1ec0414b46f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package punkt to /home/nhom6nth/nltk_data...\n",
      "[nltk_data]   Package punkt is already up-to-date!\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import nltk\n",
    "nltk.download('punkt')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "c8b20368-79c5-4841-8975-27cab37fb397",
   "metadata": {},
   "outputs": [],
   "source": [
    "result=word_tokenize(stpword)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "9d1c98f1-4075-473f-a1ec-3ea428d158c0",
   "metadata": {},
   "outputs": [],
   "source": [
    "final=[]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "9780ff8f-d7c1-46b6-8bc0-cec8d3bb687c",
   "metadata": {},
   "outputs": [],
   "source": [
    "for i in result:\n",
    "    if i not in stopwords:\n",
    "        final.append(i)\n",
    "        final.append(\" \")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "1818d3bc-ec2e-41df-918a-a0d4697732ec",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'# # stopwords.txt # # freely available stopword list , balancing coverage size . # # http : //www.lextek.com/manuals/onix/stopwords1.html across almost alone along already also although always among another anybody anyone anything anywhere area areas around ask asked asking asks away b back backed backing backs became become becomes began behind beings best better big c came case cases certain certainly clear clearly come could differ different differently done downed downing downs e early either end ended ending ends enough even evenly ever every everybody everyone everything everywhere f face faces fact facts far felt find finds first four full fully furthered furthering furthers g gave general generally get gets give given gives go going good goods got great greater greatest group grouped grouping groups h high high high higher highest however important interest interested interesting interests j k keep keeps kind knew know known knows l large largely last later latest least less let lets like likely long longer longest made make making man many may member members men might mostly mr mrs much must n necessary need needed needing needs never new new newer newest next nobody non noone nothing nowhere number numbers often old older oldest one open opened opening opens order ordered ordering orders others p part parted parting parts per perhaps place places point pointed pointing points possible present presented presenting presents problem problems put puts q quite r rather really right right room rooms said saw say says second seconds see seem seemed seeming seems sees several shall show showed showing shows side sides since small smaller smallest somebody someone something somewhere state states still still sure take taken therefore thing things think thinks though thought thoughts three thus today together took toward turn turned turning turns two u upon us use used uses v w want wanted wanting wants way ways well wells went whether whole whose within without work worked working works would x year years yet young younger youngest z '"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"\".join(final)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b753f760-5700-48c3-8a27-a44af7f5af74",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
